name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: install
        run: sudo apt-get install fuse libfuse-dev
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: build
        run: cmake --build build
      - name: test
        run: cd build && ctest -V
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/securefs
          name: securefs-binary-ubuntu-debug
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: install
        run: brew install macfuse
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: build
        run: cmake --build build
      - name: test
        run: cd build && ctest -V
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/securefs
          name: securefs-binary-macos-debug
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: install
        run: choco install winfsp
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: build
        run: cmake --build build --config Debug
      - name: test
        run: cd build && ctest -V -C Debug
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: build/Debug/securefs.exe
          name: securefs-binary-win-debug.exe
