name: C/C++ CI

on: [push, pull_request]

env:
  PYTHONUTF8: 1
  GITHUB_TOKEN: ${{ github.token }}
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get latest Github release of vcpkg
        uses: cardinalby/git-get-release-action@v1
        id: get-latest-vcpkg-release
        with:
          latest: true
          repo: microsoft/vcpkg
          prerelease: false
          draft: false
      - name: checkout-vcpkg
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/vcpkg
          repository: microsoft/vcpkg
          ref: '${{ steps.get-latest-vcpkg-release.outputs.tag_name }}'
          fetch-depth: 1
      - name: Test in FreeBSD
        id: freebsd
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          envs: "GITHUB_TOKEN VCPKG_ROOT"
          release: "13.3"
          prepare: |
            pkg install -y cmake git python39 zip curl pkgconf ninja fusefs-libs
            kldload fusefs
            sh $VCPKG_ROOT/bootstrap-vcpkg.sh
          run: |
            cd ${{ github.workspace }} && python3.9 build.py --enable_unit_test --enable_integration_test --vcpkg_root=$VCPKG_ROOT --build_root=./build --lto
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{ github.workspace }}/build/securefs
          name: securefs-freebsd-amd64
